### ISSUE TITLE
v0.7.1 fails to install

### ISSUE THREAD

**Issue by zanechua** [FleekHQ/apollo-cursor-pagination#37]
I've a project that has this package in it and when using the latest `v0.7.1`, the package fails to get built properly.

If I strictly set the `v0.7.0` version in `package.json`, everything works as expected with the following files in `node_modules/apollo-cursor-pagination/dist`

![image](https://user-images.githubusercontent.com/4265429/83372720-bc9f6100-a3f8-11ea-8d65-e004b5e49446.png)

But the moment I set it to a loose version e.g. `^0.7.0` which automatically selects `v0.7.1`, The files in  `node_modules/apollo-cursor-pagination/dist`

![image](https://user-images.githubusercontent.com/4265429/83372776-eb1d3c00-a3f8-11ea-9c02-60620b27e51d.png)

The `builder` and `orm-connectors` folders are entirely missing. Did any other change occur?

**Comment by dmerrill6** [comment]
Hello @zanechua 

Thanks for reporting.

It has been fixed in version 0.7.3. Sorry about that!
